spring:
  application:
    name: spring-app
  datasource:
    url: jdbc:mysql://localhost:3306/practise_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
