spring:
  application:
    name: spring-app
  datasource:
    url: jdbc:mysql://localhost:3306/practise_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
    mapper-locations: classpath*:com/kashibuchikyamin/spring_app/infrastructure/datasource/mapper/**/*.xml
    type-aliases-package: com.kashibuchikyamin.spring_app.infrastructure.datasource.entity
  sql:
    init:
      schema-locations: classpath:schema-mysql.sql
      mode: always
server:
  port: 8080