services:
  practise_db:
    container_name: db
    image: mysql:8.4.6
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - mysql-store:/var/lib/mysql
      - ./mysql:/data
    working_dir: /data
    environment:
      MYSQL_DATABASE: practise_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  mysql-store:

